### PR TITLE
Don't check url fully-qualified domain names

### PR DESCRIPTION
**Pull request by petrbel**
Because it doesn't work in docker-compose.

**Squash**

### CODE REVIEW

**Comment by petrbel** [comment]
@Teyras @blazekadam any ideas why the tests are failing?

**Comment by blazekadam** [comment]
Nope, no idea. They passed locally at my ntb.

**Comment by blazekadam** [comment]
what happened?

**Comment by petrbel** [comment]
no idea, after last @Teyras's rebuild everything passed... I created an issue for that (#58)

**Pull request merged**
